# Generated by Django 5.0 on 2023-12-10 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='wardno',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customers',
            name='provience',
            field=models.CharField(choices=[('KP', 'Karnali Provience'), ('BP', 'Bagmati Provience'), ('GP', 'Gandaki Provience'), ('LP', 'Lumbini Pradesh'), ('KO', 'Koshi Pradesh'), ('MP', 'Madesh Pradesh'), ('SP', 'Sudurpashim pradesh')], default='Karnali Provience', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('E', 'Electronics'), ('TR', 'Tools and Requirement'), ('CA', 'Clothing and Apparel'), ('HGF', 'Home and Garden Furniture'), ('BP', 'Beauty and Personal Care'), ('SO', 'Sports and Outdoors:'), ('OF', 'Office furniture'), ('G', 'Groceries')], default='Mobile', max_length=3),
        ),
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('shopname', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('panano', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
