# Generated by Django 5.0 on 2023-12-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customers_wardno_alter_customers_provience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='product_image_backside',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_bottomside',
            field=models.ImageField(default='', upload_to='productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_frontside',
            field=models.ImageField(default='', upload_to='productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_leftside',
            field=models.ImageField(default='', upload_to='productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_rightside',
            field=models.ImageField(default='', upload_to='productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_topside',
            field=models.ImageField(default='', upload_to='productimage'),
        ),
    ]
