# Generated by Django 5.0 on 2023-12-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_subcategory_product_upload_date_product_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_backside',
            field=models.ImageField(blank=True, default='', upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_bottomside',
            field=models.ImageField(blank=True, default='', upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_leftside',
            field=models.ImageField(blank=True, default='', upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_rightside',
            field=models.ImageField(blank=True, default='', upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_topside',
            field=models.ImageField(blank=True, default='', upload_to='productimage'),
        ),
    ]
