# Generated by Django 5.0 on 2023-12-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_shopname_alter_product_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_backside',
            field=models.ImageField(default='', upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_bottomside',
            field=models.ImageField(default='', upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_leftside',
            field=models.ImageField(default='', upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_rightside',
            field=models.ImageField(default='', upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_topside',
            field=models.ImageField(default='', upload_to='productimage'),
        ),
    ]
