# Generated by Django 5.0 on 2023-12-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_product_image_backside_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TE', 'Tools And Equipment'), ('OF', 'Office furniture'), ('AC', 'Art And Craft'), ('BF', 'Boys Fashion'), ('GF', 'Girls Fashion'), ('MF', 'Men Fashion'), ('WF', 'Women Fashion'), ('B', 'Baby'), ('E', 'Electronics'), ('BP', 'Beauty And Personal Care'), ('SO', 'Sports And Outdoors:'), ('TG', 'Toys And Games'), ('BS', 'Books And Stationry'), ('PS', 'Pet Suppliers'), ('DP', 'Digital Product'), ('FB', 'Food And Beverage'), ('AM', 'Automotive'), ('KA', 'kitchen And Appliances'), ('G', 'Groceries')], default='Mobile', max_length=3),
        ),
    ]
