# Generated by Django 5.0 on 2023-12-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorModel',
        ),
    ]
