# Generated by Django 5.0 on 2023-12-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_orderedplaced_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The way', 'On The way'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
