# Generated by Django 5.0 on 2023-12-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_orderedplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedplaced',
            name='city',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='email',
            field=models.EmailField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='phoneno',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='provience',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='wardno',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='zipcode',
            field=models.CharField(default='', max_length=150),
        ),
    ]
