# Generated by Django 5.0 on 2023-12-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_orderedplaced_city_orderedplaced_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedplaced',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderedplaced',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderedplaced',
            name='location',
        ),
        migrations.RemoveField(
            model_name='orderedplaced',
            name='phoneno',
        ),
        migrations.RemoveField(
            model_name='orderedplaced',
            name='provience',
        ),
        migrations.RemoveField(
            model_name='orderedplaced',
            name='wardno',
        ),
        migrations.RemoveField(
            model_name='orderedplaced',
            name='zipcode',
        ),
    ]
