# Generated by Django 5.0 on 2023-12-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_orderedplaced_city_remove_orderedplaced_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedplaced',
            name='city',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='email',
            field=models.EmailField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='provience',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
