# Generated by Django 5.0 on 2023-12-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_orderedplaced_city_orderedplaced_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedplaced',
            name='wardno',
            field=models.IntegerField(default=1),
        ),
    ]
