# Generated by Django 5.0 on 2023-12-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_orderedplaced_wardno'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedplaced',
            name='product_owner',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='shopname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
