# Generated by Django 5.0 on 2023-12-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_product_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedplaced',
            name='owner_email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
